/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.core.ge.style.validation

import de.jabc.cinco.meta.core.ge.style.model.validator.StylesValidator
import org.eclipse.xtext.validation.Check
import style.Image
import style.StylePackage

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class StyleValidator extends AbstractStyleValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
	public static val NO_PATH = 'noPathSpecified'
	public static val INVALID_PATH = 'invalidPath'
	
	@Check
 	def checkImagePath (Image image) {
 		if (image.path.nullOrEmpty)
 			warning('No Path specified', StylePackage.Literals.IMAGE__PATH, NO_PATH)
 		
 		val retVal = StylesValidator.checkImagePath(image, image.path) as String
 		if (!retVal.empty)
 			error(retVal, StylePackage.Literals.IMAGE__PATH, INVALID_PATH)
 	}
	
}
