build:
  artifacts:
    paths:
      - /builds/scce/cinco/de.jabc.cinco.meta.product/target/products/*.zip
    expire_in: 1 week
  cache:
    paths:
      - ~/.m2/repository
  image: maven:3.5
  stage: build
  script:
    - export MAVEN_OPTS="-Dsun.lang.ClassLoader.allowArraySyntax=true -Dmaven.repo.local=~/.m2/repository -Xms128m -Xmx2048m"
    - pushd de.jabc.cinco.meta.libraries
    - mvn -e clean package
    - popd;
    - mvn -e clean package
