build:
  artifacts:
    paths:
      - /builds/scce/cinco/de.jabc.cinco.meta.product/target/products/*.zip
    expire_in: 1 week
  before_script:
    - mkdir -p ~/.m2/repository
  cache:
    paths:
      - ~/.m2/repository
    key: maven
  image: maven:3.5
  only:
    - schedules
  stage: build
  script:
    - pushd de.jabc.cinco.meta.libraries
    - mvn -e clean package
    - popd;
    - mvn -e clean package
  variables:
    MAVEN_OPTS: "-Dsun.lang.ClassLoader.allowArraySyntax=true -Dmaven.repo.local=~/.m2/repository -Xms128m -Xmx2048m"
