build:
  before_script:
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in $DELIVERY_CINCO_SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$DELIVERY_CINCO_SSH_PRIVATE_KEY")
  cache:
    paths:
      - ~/.m2/repository
    key: maven
  image: registry.gitlab.com/scce/cinco:latest
  only:
    - schedules
    - web
  stage: build
  script:
    - pushd de.jabc.cinco.meta.libraries
    - mvn -e clean package
    - popd;
    - mvn -e clean package
    - rsync -e "ssh" de.jabc.cinco.meta.product/target/products/*.zip cincodaily@$DELIVERY_HOST:/var/www/cinco/nightly/$(date +%F)-${CI_COMMIT_SHA:0:8}/
  variables:
    DELIVERY_HOST: ls5vs001.cs.tu-dortmund.de
