/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.productdefinition.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CPDUiModule extends de.jabc.cinco.meta.productdefinition.ui.AbstractCPDUiModule {
	public CPDUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
