/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.productdefinition.validation

import ProductDefinition.About
import ProductDefinition.CincoProduct
import ProductDefinition.ProductDefinitionPackage
import java.io.File
import org.eclipse.core.resources.ResourcesPlugin
import org.eclipse.core.runtime.Platform
import org.eclipse.emf.ecore.EStructuralFeature
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class CPDValidator extends AbstractCPDValidator {

//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkImage16Exists(CincoProduct cpd){
		if(!cpd.image16.nullOrEmpty &&!cpd.image16.equals("\"\"")){
			if(!(new File(cpd.image16.replaceAll("\"",""))).exists){
				printFileDoesNotExistError(cpd.image16.replaceAll("\"",""),ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE16)
			}
		}if(!cpd.image16.nullOrEmpty &&cpd.image16.equals("\"\"")){
			error("Please enter the Path to the Image",ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE16)
		}		
	}
	@Check
	def checkImage32Exists(CincoProduct cpd){
		if(!cpd.image32.nullOrEmpty &&!cpd.image32.equals("\"\"")){
			if(!(new File(cpd.image32.replaceAll("\"",""))).exists){
				printFileDoesNotExistError(cpd.image32.replaceAll("\"",""),ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE32)
			}
		}if(!cpd.image32.nullOrEmpty &&cpd.image32.equals("\"\"")){
			error("Please enter the Path to the Image",ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE32)
		}		
	}
	@Check
	def checkImage48Exists(CincoProduct cpd){
		if(!cpd.image48.nullOrEmpty &&!cpd.image48.equals("\"\"")){
			if(!(new File(cpd.image48.replaceAll("\"",""))).exists){
				printFileDoesNotExistError(cpd.image48.replaceAll("\"",""),ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE48)
			}
		}if(!cpd.image48.nullOrEmpty &&cpd.image48.equals("\"\"")){
			error("Please enter the Path to the Image",ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE48)
		}		
	}
	@Check
	def checkImage64Exists(CincoProduct cpd){
		if(!cpd.image64.nullOrEmpty &&!cpd.image64.equals("\"\"")){
			if(!(new File(cpd.image64.replaceAll("\"",""))).exists){
				printFileDoesNotExistError(cpd.image64.replaceAll("\"",""),ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE64)
			}
		}if(!cpd.image64.nullOrEmpty &&cpd.image64.equals("\"\"")){
			error("Please enter the Path to the Image",ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE64)
		}		
	}
	@Check
	def checkImage128Exists(CincoProduct cpd){
		if(!cpd.image128.nullOrEmpty &&!cpd.image128.equals("\"\"")){
			if(!(new File(cpd.image128.replaceAll("\"",""))).exists){
				printFileDoesNotExistError(cpd.image128.replaceAll("\"",""),ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE128)
			}
		}if(!cpd.image128.nullOrEmpty &&cpd.image128.equals("\"\"")){
			error("Please enter the Path to the Image",ProductDefinitionPackage.Literals.CINCO_PRODUCT__IMAGE128)
		}		
	}
	@Check
	def checkAboutImageExists(About about){
		if(!about.imagePath.nullOrEmpty &&!about.imagePath.equals("\"\"")){
			if(!(new File(about.imagePath.replaceAll("\"",""))).exists){
				printFileDoesNotExistError(about.imagePath.replaceAll("\"",""),ProductDefinitionPackage.Literals.ABOUT__IMAGE_PATH)
			}
		}if(!about.imagePath.nullOrEmpty &&about.imagePath.equals("\"\"")){
			error("Please enter the Path to the Image",ProductDefinitionPackage.Literals.ABOUT__IMAGE_PATH)
		}
	}
	@Check
	def checkBundleContainsSplashImage(CincoProduct cpd){
		var splashScreen = cpd.splashPlugin.replaceAll("\"","")
		if(!splashScreen.nullOrEmpty){
			if(!splashScreen.endsWith("splash.bmp"))
				error("Please enter the path to the splash.bmp",ProductDefinitionPackage.Literals.CINCO_PRODUCT__SPLASH_PLUGIN)
			var splashScreenFile = new File(splashScreen)
			if(!splashScreenFile.exists){
				println(splashScreen)
				error("splash.bmp does not exist",ProductDefinitionPackage.Literals.CINCO_PRODUCT__SPLASH_PLUGIN)
				
				}
		}else{
			error("Please enter the path to the splash.bmp",ProductDefinitionPackage.Literals.CINCO_PRODUCT__SPLASH_PLUGIN)
		}
	}
	
	
	
	def printFileDoesNotExistError(String fileName, EStructuralFeature feature) {
		error(String.format("File %s does not exist",fileName),feature)
	}
	
}
