/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.core.mgl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MGLRuntimeModule extends de.jabc.cinco.meta.core.mgl.AbstractMGLRuntimeModule {

}
