/*
* generated by Xtext
*/
package de.jabc.cinco.meta.core.mgl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MGLStandaloneSetup extends MGLStandaloneSetupGenerated{

	public static void doSetup() {
		new MGLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

