/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.productdefinition.ui.contentassist

import de.jabc.cinco.meta.productdefinition.ui.contentassist.AbstractCPDProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CPDProposalProvider extends AbstractCPDProposalProvider {
}
