<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cincoapi" nsURI="http://cinco.scce.info/api" nsPrefix="cincoapi">
  <eClassifiers xsi:type="ecore:EClass" name="CNode" eSuperTypes="../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//Node #//CModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CContainer" eSuperTypes="../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//Container #//CModelElementContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="CEdge" eSuperTypes="../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//Edge #//CModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CGraphModel" eSuperTypes="../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//GraphModel #//CModelElementContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="CModelElementContainer" abstract="true"
      eSuperTypes="../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//ModelElementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/PictogramElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CModelElement" abstract="true" eSuperTypes="../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/PictogramElement"/>
  </eClassifiers>
</ecore:EPackage>
