/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.core.ge.style;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StyleRuntimeModule extends de.jabc.cinco.meta.core.ge.style.AbstractStyleRuntimeModule {

}
