/*
* generated by Xtext
*/
package de.jabc.cinco.meta.core.ge.style;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class StyleStandaloneSetup extends StyleStandaloneSetupGenerated{

	public static void doSetup() {
		new StyleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

