/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.productdefinition;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CPDRuntimeModule extends de.jabc.cinco.meta.productdefinition.AbstractCPDRuntimeModule {

}
