/*
* generated by Xtext
*/
package de.jabc.cinco.meta.productdefinition;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CPDStandaloneSetup extends CPDStandaloneSetupGenerated{

	public static void doSetup() {
		new CPDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

