package de.ls5.cinco.transformation.api;

import de.ls5.dywa.generated.entity.Point;

/**
 * Generated by Pyro CINCO Meta Plugin
 */
public class CBendingpointImpl implements CBendingpoint{
    private Point point;

    public CBendingpointImpl(){}

    public CBendingpointImpl(Point point) {
        this.point = point;
    }

    public Point getPoint() {
        return point;
    }

    public void setPoint(Point point) {
        this.point = point;
    }
}
