package de.ls5.cinco.transformation.api;

import de.ls5.dywa.generated.entity.ModelElement;

/**
 * Generated by Pyro CINCO Meta Plugin
 */
public interface CModelElement extends CIdentifiableElement{

    public void setModelElement(ModelElement modelElement);

    public ModelElement getModelElement();

    @Deprecated
    abstract void update();

    abstract boolean delete();

    public abstract <T extends CGraphModel> T getCRootElement();

    public abstract CModelElementContainer getContainer();

    public abstract void setContainer(CModelElementContainer container);



}
