/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.core.mgl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MGLUiModule extends de.jabc.cinco.meta.core.mgl.ui.AbstractMGLUiModule {
	public MGLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
