/*
 * generated by Xtext
 */
package de.jabc.cinco.meta.core.ge.style.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StyleUiModule extends de.jabc.cinco.meta.core.ge.style.ui.AbstractStyleUiModule {
	public StyleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
