<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graphicalgraphmodel" nsURI="http://cinco.scce.info/graphicalgraphmodel"
    nsPrefix="graphicalgraphmodel">
  <eClassifiers xsi:type="ecore:EClass" name="GModelElementContainer" abstract="true"
      interface="true">
    <eOperations name="getModelElements" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(GModelElement e: this.getModelElements()){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e)){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e));&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//GModelElementContainer/getModelElements/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//GModelElement"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//GModelElementContainer/getModelElements/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getAllNodes" upperBound="-1" eType="#//GNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getModelElements(GNode.class);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllEdges" upperBound="-1" eType="#//GEdge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getModelElements(GEdge.class);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllContainers" upperBound="-1" eType="#//GContainer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getModelElements(GContainer.class);"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//GModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GContainer" eSuperTypes="#//GModelElementContainer #//GNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="GGraphModel" abstract="true" eSuperTypes="#//GModelElementContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphModel" lowerBound="1"
        eType="ecore:EClass ../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//GraphModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Diagram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GEdge" eSuperTypes="#//GModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElement" lowerBound="1"
        eType="#//GNode" eOpposite="#//GNode/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" lowerBound="1"
        eType="#//GNode" eOpposite="#//GNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Connection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GNode" eSuperTypes="#//GModelElement">
    <eOperations name="getSuccessors" upperBound="-1" eType="#//GNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;GNode> list = new org.eclipse.emf.common.util.BasicEList&lt;GNode>();&#xA;&#x9;&#x9;for(GEdge e: this.getOutgoing()){&#xA;&#x9;&#x9;&#x9;list.add(e.getTargetElement());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getSuccessors" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(GEdge e: this.getOutgoing()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e.getTargetElement())){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e.getTargetElement()));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//GNode/getSuccessors.1/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//GNode"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//GNode/getSuccessors.1/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getPredecessors" upperBound="-1" eType="#//GNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;GNode> list = new org.eclipse.emf.common.util.BasicEList&lt;GNode>();&#xA;&#x9;&#x9;for(GEdge e: this.getIncoming()){&#xA;&#x9;&#x9;&#x9;list.add(e.getSourceElement());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getPredecessors" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(GEdge e: this.getIncoming()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e.getSourceElement())){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e.getSourceElement()));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//GNode/getPredecessors.1/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//GNode"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//GNode/getPredecessors.1/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getIncoming" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(GEdge e: this.getIncoming()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e)){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//GNode/getIncoming/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//GEdge"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//GNode/getIncoming/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getOutgoing" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(GEdge e: this.getOutgoing()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e)){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//GNode/getOutgoing/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//GEdge"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//GNode/getOutgoing/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//GEdge" eOpposite="#//GEdge/targetElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//GEdge" eOpposite="#//GEdge/sourceElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/ContainerShape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GModelElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//GModelElementContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" eType="ecore:EClass ../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Diagram"/>
  </eClassifiers>
</ecore:EPackage>
