<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graphicalgraphmodel" nsURI="http://cinco.scce.info/graphicalgraphmodel"
    nsPrefix="graphicalgraphmodel">
  <eClassifiers xsi:type="ecore:EClass" name="CModelElementContainer" abstract="true"
      interface="true">
    <eOperations name="getCModelElements" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(CModelElement e: this.getModelElements()){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e)){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e));&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//CModelElementContainer/getCModelElements/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//CModelElement"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//CModelElementContainer/getCModelElements/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getAllCNodes" upperBound="-1" eType="#//CNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getCModelElements(CNode.class);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllCEdges" upperBound="-1" eType="#//CEdge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getCModelElements(CEdge.class);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAllCContainers" upperBound="-1" eType="#//CContainer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getCModelElements(CContainer.class);"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//CModelElement" containment="true" eOpposite="#//CModelElement/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="map" upperBound="-1" eType="#//ModelElementToCModelElementMap"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CContainer" eSuperTypes="#//CModelElementContainer #//CNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CGraphModel" abstract="true" eSuperTypes="#//CModelElementContainer">
    <eOperations name="getPictogramElement" eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/ContainerShape">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return this.getShape();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" lowerBound="1"
        eType="ecore:EClass ../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//GraphModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shape" eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/ContainerShape"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CEdge" eSuperTypes="#//CModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElement" lowerBound="1"
        eType="#//CNode" eOpposite="#//CNode/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElement" lowerBound="1"
        eType="#//CNode" eOpposite="#//CNode/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CNode" eSuperTypes="#//CModelElement">
    <eOperations name="getSuccessors" upperBound="-1" eType="#//CNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;CNode> list = new org.eclipse.emf.common.util.BasicEList&lt;CNode>();&#xA;&#x9;&#x9;for(CEdge e: this.getOutgoing()){&#xA;&#x9;&#x9;&#x9;list.add(e.getTargetElement());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getSuccessors" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(CEdge e: this.getOutgoing()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e.getTargetElement())){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e.getTargetElement()));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//CNode/getSuccessors.1/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//CNode"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//CNode/getSuccessors.1/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getPredecessors" upperBound="-1" eType="#//CNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;CNode> list = new org.eclipse.emf.common.util.BasicEList&lt;CNode>();&#xA;&#x9;&#x9;for(CEdge e: this.getIncoming()){&#xA;&#x9;&#x9;&#x9;list.add(e.getSourceElement());&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getPredecessors" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(CEdge e: this.getIncoming()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e.getSourceElement())){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e.getSourceElement()));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//CNode/getPredecessors.1/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//CNode"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//CNode/getPredecessors.1/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getIncoming" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(CEdge e: this.getIncoming()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e)){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//CNode/getIncoming/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//CEdge"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//CNode/getIncoming/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getOutgoing" upperBound="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="EList&lt;T> list = new org.eclipse.emf.common.util.BasicEList&lt;T>();&#xA;&#x9;&#x9;if(clazz!=null){&#xA;&#x9;&#x9;&#x9;for(CEdge e: this.getOutgoing()){&#xA;&#x9;&#x9;&#x9;&#x9;if(clazz.isInstance(e)){&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;list.add(clazz.cast(e));&#xA;&#x9;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;&#x9;}&#xA;&#x9;&#x9;}else{&#xA;&#x9;&#x9;&#x9;throw new NullPointerException(&quot;Class must not be null.&quot;);&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return org.eclipse.emf.common.util.ECollections.unmodifiableEList(list);"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//CNode/getOutgoing/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//CEdge"/>
      </eTypeParameters>
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
          <eTypeArguments eTypeParameter="#//CNode/getOutgoing/T"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getPictogramElement().getGraphicsAlgorithm().getX();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getPictogramElement().getGraphicsAlgorithm().getY();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getPictogramElement().getGraphicsAlgorithm().getWidth();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getPictogramElement().getGraphicsAlgorithm().getHeight();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setX">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="getPictogramElement().getGraphicsAlgorithm().setX(x);"/>
      </eAnnotations>
      <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setY">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="getPictogramElement().getGraphicsAlgorithm().setY(y);"/>
      </eAnnotations>
      <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setWidth">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="getPictogramElement().getGraphicsAlgorithm().setWidth(width);"/>
      </eAnnotations>
      <eParameters name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="setHeight">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="getPictogramElement().getGraphicsAlgorithm().setHeight(height);"/>
      </eAnnotations>
      <eParameters name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//CEdge" eOpposite="#//CEdge/targetElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//CEdge" eOpposite="#//CEdge/sourceElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CModelElement" abstract="true" interface="true">
    <eOperations name="getDiagram" eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/Diagram">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getCRootElement().getDiagram();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getCRootElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="CModelElementContainer container = this.getContainer();&#xA;if(container!=null){&#xA;&#x9;while(container != null &amp;&amp; !(container instanceof CGraphModel))&#xA;&#x9;&#x9;container = ((graphicalgraphmodel.CModelElement) container).getContainer();&#xA;&#x9;&#x9;if(container!=null)&#xA;&#x9;&#x9;&#x9;return (T) container;&#xA;&#x9;&#x9;}&#xA;&#x9;&#x9;&#xA;&#x9;&#x9;return null;"/>
      </eAnnotations>
      <eGenericType eTypeParameter="#//CModelElement/getCRootElement/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//CGraphModel"/>
      </eTypeParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//CModelElementContainer"
        eOpposite="#//CModelElementContainer/modelElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElement" eType="ecore:EClass ../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictogramElement" eType="ecore:EClass ../../org.eclipse.graphiti.mm/model/graphiti.ecore#//pictograms/PictogramElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementToCModelElementMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass ../../de.jabc.cinco.meta.core.mgl.model/model/GraphModel.ecore#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//CModelElement"/>
  </eClassifiers>
</ecore:EPackage>
